//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoE_Leveling_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoE_Leveling_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream alert {
            get {
                return ResourceManager.GetStream("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Twilight Strand
        ///The Coast
        ///The Tidal Island
        ///The Mud Flats
        ///The Fetid Pool
        ///The Submerged Passage
        ///The Flooded Depths
        ///The Ledge
        ///The Climb
        ///The Lower Prison
        ///The Upper Prison
        ///Prisoner&apos;s Gate
        ///The Ship Graveyard
        ///The Cavern of Wrath
        ///The Ship Graveyard Cave
        ///The Cavern of Anger
        ///Lioneye&apos;s Watch
        ///The Southern Forest
        ///The Old Fields
        ///The Den
        ///The Crossroads
        ///The Chamber of Sins Level 1
        ///The Riverways
        ///The Fellshrine Ruins
        ///The Broken Bridge
        ///The Chamber of Sins Level 2
        ///The Crypt Level 1
        ///The Western Fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string areas_part1 {
            get {
                return ResourceManager.GetString("areas_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Twilight Strand
        ///The Coast
        ///The Tidal Island
        ///The Mud Flats
        ///The Karui Fortress
        ///The Ridge
        ///The Lower Prison
        ///Shavronne&apos;s Tower
        ///Prisoner&apos;s Gate
        ///The Riverways
        ///The Wetlands
        ///The Western Forest
        ///The Southern Forest
        ///The Cavern of Anger
        ///The Beacon
        ///The Brine King&apos;s Reef
        ///Lioneye&apos;s Watch
        ///The Broken Bridge
        ///The Crossroads
        ///The Fellshrine Ruins
        ///The Crypt
        ///The Chamber of Sins Level 1
        ///The Chamber of Sins Level 2
        ///Maligaro&apos;s Sanctum
        ///The Den
        ///The Ashen Fields
        ///The Northern Forest
        ///The Dread Thicket
        ///The Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string areas_part2 {
            get {
                return ResourceManager.GetString("areas_part2", resourceCulture);
            }
        }
    }
}
